# This workflow will build and ran frogbot current changes (and not the official released action) as sanity check.
name: "Frogbot Sanity"
on:
  # Use the main frogbot.yml to trigger this workflow.
  workflow_run:
    workflows: ["Frogbot"]
    types:
      - completed
jobs:
  dev-frogbot-scan:
    # Make sure this workflow runs only if the frogbot ran successfully (authorized by maintainer)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build Frogbot
        run: buildscripts/build.sh
      - name: Scan
        env:
          # [Mandatory] JFrog platform URL
          JF_URL: ${{ secrets.FROGBOT_URL }}

          # [Mandatory if JF_USER and JF_PASSWORD are not provided] 
          JF_ACCESS_TOKEN: ${{ secrets.FROGBOT_ACCESS_TOKEN }}
          
          # [Manadatory] The GitHub token automatically generated for the job
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          JF_GIT_BASE_BRANCH: ${{ github.base_ref}}
          JF_GIT_PULL_REQUEST_ID: ${{ github.event.number }}
          JF_GIT_PROVIDER: "github"
          JF_GIT_OWNER: ${{ github.repository_owner }}
          JF_GIT_REPO: ${{ github.event.repository.name }} 
        run: ./frogbot scan-pull-request